[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_OPENWEATHER_API_KEY = "3e0527c3c27a23f93bb896188458c8a6"
